version: "3.9"
services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - ./imports/keycloak:/opt/jboss/keycloak/imports
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/dev-realm-export.json
#    command:
#      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/dev-realm-export.json"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5431"

  service-discovery:
    build:
      context: service-discovery
    image: tannerlankford/eureka-server:latest
    container_name: service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GATEWAY_SECRET=${GATEWAY_SECRET}
    ports:
      - "8761:8761"

volumes:
  postgres_data:
    driver: local