version: "3.9"
services:
  service-discovery:
    build:
      context: service-discovery
    image: tannerlankford/eureka-server:latest
    container_name: service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GATEWAY_SECRET=${GATEWAY_SECRET}
    ports:
      - "8761:8761"
