version: "3.9"

# This Docker-Compose file creates databases for each service as well as any tools used for testing and QA. Ports are
# exposed, so they can be used by locally ran instances of the backend services for development.
services:
  products-service-db:
    image: postgres:14
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data/
  SonarQube:
    image: sonarqube:lts-community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"

  sonar-db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${SONAR_USER}
      POSTGRES_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data


volumes:
  db-data-dev:
    driver: local
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  sonar_db:
  sonar_db_data: