spring:
  security:
    user:
      name: admin
      password: admin

server:
  port: 8761

eureka:
  instance:
    hostname: service-discovery
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'