server:
  shutdown: graceful
  port: 8000

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://product-service-db:5432/product
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    show-sql: true
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yml"
    enabled: true
    parameters:
      textColumnType: TEXT
    contexts: dev

graphql:
  servlet:
    max-query-depth: 100
    exception-handlers-enabled: true
    tracing-enabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
  extended-scalars: NonNegativeInt, NonNegativeFloat

voyager:
  enabled: true

logging:
  level:
    com:
    org:
      springframework: debug
      hibernate: debug
    "liquibase": info
    root: info

management:
  endpoint:
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
