server:
  shutdown: graceful
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://product-service-db:5432/product
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

graphql:
  servlet:
    max-query-depth: 100
    exception-handlers-enabled: true
    tracing-enabled: true
  playground:
    headers:
      Authorization: Bearer TOKEN
  extended-scalars: NonNegativeInt, NonNegativeFloat

okta:
  oauth2:
    client-id: ${ENV_OKTA_CLIENT_ID}
    issuer: ${ENV_OKTA_ISSUER_URL}

voyager:
  enabled: true

logging:
  pattern:
    console: -%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n%wEx